In [1]:
!pip install mlflow

Requirement already satisfied: mlflow in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (3.2.0)
Requirement already satisfied: mlflow-skinny==3.2.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (3.2.0)
Requirement already satisfied: mlflow-tracing==3.2.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (3.2.0)
Requirement already satisfied: Flask<4 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (3.1.1)
Requirement already satisfied: alembic!=1.10.0,<2 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (1.16.4)
Requirement already satisfied: docker<8,>=4.0.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (7.1.0)
Requirement already satisfied: graphene<4 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (3.4.3)
Requirement already satisfied: matplotlib<4 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (3.10.1)
Requirement already satisfied: numpy<3 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (2.1.3)
Requirement already satisfied: pandas<3 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (2.2.3)
Requirement already satisfied: pyarrow<22,>=4.0.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (20.0.0)
Requirement already satisfied: scikit-learn<2 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (1.7.1)
Requirement already satisfied: scipy<2 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (1.15.2)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (2.0.43)
Requirement already satisfied: waitress<4 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (3.0.2)
Requirement already satisfied: cachetools<7,>=5.0.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (5.5.2)
Requirement already satisfied: click<9,>=7.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (8.1.8)
Requirement already satisfied: cloudpickle<4 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (3.1.1)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (0.63.0)
Requirement already satisfied: fastapi<1 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (0.116.1)
Requirement already satisfied: gitpython<4,>=3.1.9 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (3.1.44)
Requirement already satisfied: importlib_metadata!=4.7.0,<9,>=3.7.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (8.7.0)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (1.36.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (1.36.0)
Requirement already satisfied: packaging<26 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (24.2)
Requirement already satisfied: protobuf<7,>=3.12.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (5.29.4)
Requirement already satisfied: pydantic<3,>=1.10.8 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (2.11.7)
Requirement already satisfied: pyyaml<7,>=5.1 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (6.0.2)
Requirement already satisfied: requests<3,>=2.17.3 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (2.32.3)
Requirement already satisfied: sqlparse<1,>=0.4.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (0.5.3)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (4.13.2)
Requirement already satisfied: uvicorn<1 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (0.35.0)
Requirement already satisfied: Mako in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from alembic!=1.10.0,<2->mlflow) (1.3.10)
Requirement already satisfied: tomli in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from alembic!=1.10.0,<2->mlflow) (2.2.1)
Requirement already satisfied: pywin32>=304 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from docker<8,>=4.0.0->mlflow) (311)
Requirement already satisfied: urllib3>=1.26.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from docker<8,>=4.0.0->mlflow) (2.4.0)
Requirement already satisfied: blinker>=1.9.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from Flask<4->mlflow) (3.0.2)
Requirement already satisfied: werkzeug>=3.1.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from Flask<4->mlflow) (3.1.3)
Requirement already satisfied: graphql-core<3.3,>=3.1 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from graphene<4->mlflow) (3.2.6)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from graphene<4->mlflow) (3.2.0)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from graphene<4->mlflow) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<4->mlflow) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<4->mlflow) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<4->mlflow) (1.4.8)
Requirement already satisfied: pillow>=8 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<4->mlflow) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<4->mlflow) (3.2.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn<2->mlflow) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn<2->mlflow) (3.6.0)
Requirement already satisfied: greenlet>=1 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.2.4)
Requirement already satisfied: colorama in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from click<9,>=7.0->mlflow-skinny==3.2.0->mlflow) (0.4.6)
Requirement already satisfied: google-auth~=2.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.2.0->mlflow) (2.40.3)
Requirement already satisfied: starlette<0.48.0,>=0.40.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from fastapi<1->mlflow-skinny==3.2.0->mlflow) (0.47.2)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.2.0->mlflow) (4.0.12)
Requirement already satisfied: zipp>=3.20 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from importlib_metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==3.2.0->mlflow) (3.23.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.57b0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.2.0->mlflow) (0.57b0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from pydantic<3,>=1.10.8->mlflow-skinny==3.2.0->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from pydantic<3,>=1.10.8->mlflow-skinny==3.2.0->mlflow) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from pydantic<3,>=1.10.8->mlflow-skinny==3.2.0->mlflow) (0.4.1)
Requirement already satisfied: six>=1.5 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.2.0->mlflow) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.2.0->mlflow) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.2.0->mlflow) (2025.1.31)
Requirement already satisfied: h11>=0.8 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from uvicorn<1->mlflow-skinny==3.2.0->mlflow) (0.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.2.0->mlflow) (5.0.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.2.0->mlflow) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.2.0->mlflow) (4.7.2)
Requirement already satisfied: anyio<5,>=3.6.2 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from starlette<0.48.0,>=0.40.0->fastapi<1->mlflow-skinny==3.2.0->mlflow) (4.10.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from anyio<5,>=3.6.2->starlette<0.48.0,>=0.40.0->fastapi<1->mlflow-skinny==3.2.0->mlflow) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from anyio<5,>=3.6.2->starlette<0.48.0,>=0.40.0->fastapi<1->mlflow-skinny==3.2.0->mlflow) (1.3.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.2.0->mlflow) (0.6.1)

[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

## All required commands to install MLflow on EC2:

https://github.com/entbappy/MLflow-Basic-Demo

In [2]:
# Test mlflow

import mlflow

# mlflow.set_tracking_uri("http://ec2-34-228-229-84.compute-1.amazonaws.com:5000/")

# with mlflow.start_run():
#     mlflow.log_param("param1", 15)
#     mlflow.log_metric("metric1", 0.89)

In [3]:
#creating baseline model

import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/Himanshu-1703/reddit-sentiment-analysis/refs/heads/main/data/reddit.csv')
df.head()

                                       clean_comment  category
0   family mormon have never tried explain them t...         1
1  buddhism has very much lot compatible with chr...         1
2  seriously don say thing first all they won get...        -1
3  what you have learned yours and only yours wha...         0
4  for your own benefit you may want read living ...         1

In [5]:
df.dropna(inplace=True)

In [6]:
df.drop_duplicates(inplace=True)

In [7]:
df = df[~(df['clean_comment'].str.strip() == '')]

In [8]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [9]:
# Ensure necessary NLTK data is downloaded
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to C:\Users\SAI
[nltk_data]     DHRUVA\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\SAI
[nltk_data]     DHRUVA\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [10]:
# Define the preprocessing function
def preprocess_comment(comment):
    # Convert to lowercase
    comment = comment.lower()

    # Remove trailing and leading whitespaces
    comment = comment.strip()

    # Remove newline characters
    comment = re.sub(r'\n', ' ', comment)

    # Remove non-alphanumeric characters, except punctuation
    comment = re.sub(r'[^A-Za-z0-9\s!?.,]', '', comment)

    # Remove stopwords but retain important ones for sentiment analysis
    stop_words = set(stopwords.words('english')) - {'not', 'but', 'however', 'no', 'yet'}
    comment = ' '.join([word for word in comment.split() if word not in stop_words])

    # Lemmatize the words
    lemmatizer = WordNetLemmatizer()
    comment = ' '.join([lemmatizer.lemmatize(word) for word in comment.split()])

    return comment

In [11]:
# Apply the preprocessing function to the 'clean_comment' column
df['clean_comment'] = df['clean_comment'].apply(preprocess_comment)

In [12]:
df.head()

                                       clean_comment  category
0  family mormon never tried explain still stare ...         1
1  buddhism much lot compatible christianity espe...         1
2  seriously say thing first get complex explain ...        -1
3  learned want teach different focus goal not wr...         0
4  benefit may want read living buddha living chr...         1

In [13]:
import mlflow
import mlflow.sklearn
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split, cross_val_predict, StratifiedKFold
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
# Step 1: Vectorize the comments using Bag of Words (CountVectorizer)
vectorizer = CountVectorizer(max_features=10000)  # Bag of Words model with a limit of 1000 features

In [15]:
X = vectorizer.fit_transform(df['clean_comment']).toarray()
y = df['category']  # Assuming 'sentiment' is the target variable (0 or 1 for binary classification)

In [16]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [17]:
X.shape

(36793, 10000)

In [18]:
y

0        1
1        1
2       -1
3        0
4        1
        ..
37244    0
37245    1
37246    0
37247    1
37248    0
Name: category, Length: 36793, dtype: int64

In [19]:
y.shape

(36793,)

In [20]:
# Step 2: Set up the MLflow tracking server
# mlflow.set_tracking_uri("mlruns")

In [21]:
# Set or create an experiment
exp=mlflow.set_experiment('/mlflow/RF Baseline')
exp

<Experiment: artifact_location=('file:C:/Users/SAI '
 'DHRUVA/Downloads/YouTube-Sentiment-Insights/notebooks/mlruns/917368509782845872'), creation_time=1756045213488, experiment_id='917368509782845872', last_update_time=1756045213488, lifecycle_stage='active', name='/mlflow/RF Baseline', tags={}>

In [22]:
# !pip install boto3

In [23]:
# !pip install awscli

In [24]:
# import os

# os.environ["AWS_ACCESS_KEY_ID"] = "AKIA2S6MXDP6YCBWGXMW"
# os.environ["AWS_SECRET_ACCESS_KEY"] = "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"
# os.environ["AWS_DEFAULT_REGION"] = "us-east-1"

In [ ]:
# Step 1: Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Step 2: Define and train a Random Forest baseline model using a simple train-test split
with mlflow.start_run(experiment_id=exp.experiment_id,
                      run_name='RandomForest_Baseline_TrainTestSplit', 
                      description="Baseline RandomForest model for sentiment analysis using Bag of Words (BoW) with a simple train-test split") as run:
    
    
    mlflow.set_tag("mlflow.runName", "RandomForest_Baseline_TrainTestSplit")
    mlflow.set_tag("experiment_type", "baseline")
    mlflow.set_tag("model_type", "RandomForestClassifier")

    # Add a description
    mlflow.set_tag("description", "Baseline RandomForest model for sentiment analysis using Bag of Words (BoW) with a simple train-test split")

    # Log parameters for the vectorizer
    mlflow.log_param("vectorizer_type", "CountVectorizer")
    mlflow.log_param("vectorizer_max_features", vectorizer.max_features)

    # Log Random Forest parameters
    n_estimators = 200
    max_depth = 15

    mlflow.log_param("n_estimators", n_estimators)
    mlflow.log_param("max_depth", max_depth)

    # Initialize and train the model
    model = RandomForestClassifier(n_estimators=n_estimators, max_depth=max_depth, random_state=42)
    model.fit(X_train, y_train)

    # Make predictions on the test set
    y_pred = model.predict(X_test)

    # Log metrics for each class and accuracy
    accuracy = accuracy_score(y_test, y_pred)
    mlflow.log_metric("accuracy", accuracy)

    classification_rep = classification_report(y_test, y_pred, output_dict=True)

    for label, metrics in classification_rep.items():
        if isinstance(metrics, dict):  # For precision, recall, f1-score, etc.
            for metric, value in metrics.items():
                mlflow.log_metric(f"{label}_{metric}", value)

    # Confusion matrix plot
    conf_matrix = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(8, 6))
    sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.title("Confusion Matrix")

    # Save and log the confusion matrix plot
    plt.savefig("confusion_matrix.png")
    mlflow.log_artifact("confusion_matrix.png")

    # Log the Random Forest model
    mlflow.sklearn.log_model(model, "random_forest_model")

    # Optionally log the dataset itself (if it's small enough)
    df.to_csv("dataset.csv", index=False)
    mlflow.log_artifact("dataset.csv")

# Display final accuracy
print(f"Accuracy: {accuracy}")

In [26]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

          -1       1.00      0.01      0.01      1650
           0       0.67      0.83      0.74      2555
           1       0.63      0.84      0.72      3154

    accuracy                           0.65      7359
   macro avg       0.77      0.56      0.49      7359
weighted avg       0.73      0.65      0.57      7359

In [27]:
df.to_csv('reddit_preprocessing.csv', index=False)

In [28]:
pd.read_csv('reddit_preprocessing.csv').head()

                                       clean_comment  category
0  family mormon never tried explain still stare ...         1
1  buddhism much lot compatible christianity espe...         1
2  seriously say thing first get complex explain ...        -1
3  learned want teach different focus goal not wr...         0
4  benefit may want read living buddha living chr...         1

In [29]:
!pip install pyngrok
!pip install mlflow
import mlflow

Requirement already satisfied: pyngrok in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (7.3.0)

[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: PyYAML>=5.1 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from pyngrok) (6.0.2)
Requirement already satisfied: mlflow in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (3.2.0)
Requirement already satisfied: mlflow-skinny==3.2.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (3.2.0)
Requirement already satisfied: mlflow-tracing==3.2.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (3.2.0)
Requirement already satisfied: Flask<4 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (3.1.1)
Requirement already satisfied: alembic!=1.10.0,<2 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (1.16.4)
Requirement already satisfied: docker<8,>=4.0.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (7.1.0)
Requirement already satisfied: graphene<4 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (3.4.3)
Requirement already satisfied: matplotlib<4 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (3.10.1)
Requirement already satisfied: numpy<3 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (2.1.3)
Requirement already satisfied: pandas<3 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (2.2.3)
Requirement already satisfied: pyarrow<22,>=4.0.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (20.0.0)
Requirement already satisfied: scikit-learn<2 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (1.7.1)
Requirement already satisfied: scipy<2 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (1.15.2)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (2.0.43)
Requirement already satisfied: waitress<4 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (3.0.2)
Requirement already satisfied: cachetools<7,>=5.0.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (5.5.2)
Requirement already satisfied: click<9,>=7.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (8.1.8)
Requirement already satisfied: cloudpickle<4 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (3.1.1)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (0.63.0)
Requirement already satisfied: fastapi<1 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (0.116.1)
Requirement already satisfied: gitpython<4,>=3.1.9 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (3.1.44)
Requirement already satisfied: importlib_metadata!=4.7.0,<9,>=3.7.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (8.7.0)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (1.36.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (1.36.0)
Requirement already satisfied: packaging<26 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (24.2)
Requirement already satisfied: protobuf<7,>=3.12.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (5.29.4)
Requirement already satisfied: pydantic<3,>=1.10.8 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (2.11.7)
Requirement already satisfied: pyyaml<7,>=5.1 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (6.0.2)
Requirement already satisfied: requests<3,>=2.17.3 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (2.32.3)
Requirement already satisfied: sqlparse<1,>=0.4.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (0.5.3)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (4.13.2)
Requirement already satisfied: uvicorn<1 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.2.0->mlflow) (0.35.0)
Requirement already satisfied: Mako in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from alembic!=1.10.0,<2->mlflow) (1.3.10)
Requirement already satisfied: tomli in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from alembic!=1.10.0,<2->mlflow) (2.2.1)
Requirement already satisfied: pywin32>=304 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from docker<8,>=4.0.0->mlflow) (311)
Requirement already satisfied: urllib3>=1.26.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from docker<8,>=4.0.0->mlflow) (2.4.0)
Requirement already satisfied: blinker>=1.9.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from Flask<4->mlflow) (3.0.2)
Requirement already satisfied: werkzeug>=3.1.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from Flask<4->mlflow) (3.1.3)
Requirement already satisfied: graphql-core<3.3,>=3.1 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from graphene<4->mlflow) (3.2.6)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from graphene<4->mlflow) (3.2.0)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from graphene<4->mlflow) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<4->mlflow) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<4->mlflow) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<4->mlflow) (1.4.8)
Requirement already satisfied: pillow>=8 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<4->mlflow) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<4->mlflow) (3.2.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn<2->mlflow) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn<2->mlflow) (3.6.0)
Requirement already satisfied: greenlet>=1 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.2.4)
Requirement already satisfied: colorama in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from click<9,>=7.0->mlflow-skinny==3.2.0->mlflow) (0.4.6)
Requirement already satisfied: google-auth~=2.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.2.0->mlflow) (2.40.3)
Requirement already satisfied: starlette<0.48.0,>=0.40.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from fastapi<1->mlflow-skinny==3.2.0->mlflow) (0.47.2)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.2.0->mlflow) (4.0.12)
Requirement already satisfied: zipp>=3.20 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from importlib_metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==3.2.0->mlflow) (3.23.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.57b0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.2.0->mlflow) (0.57b0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from pydantic<3,>=1.10.8->mlflow-skinny==3.2.0->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from pydantic<3,>=1.10.8->mlflow-skinny==3.2.0->mlflow) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from pydantic<3,>=1.10.8->mlflow-skinny==3.2.0->mlflow) (0.4.1)
Requirement already satisfied: six>=1.5 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.2.0->mlflow) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.2.0->mlflow) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.2.0->mlflow) (2025.1.31)
Requirement already satisfied: h11>=0.8 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from uvicorn<1->mlflow-skinny==3.2.0->mlflow) (0.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.2.0->mlflow) (5.0.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.2.0->mlflow) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.2.0->mlflow) (4.7.2)
Requirement already satisfied: anyio<5,>=3.6.2 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from starlette<0.48.0,>=0.40.0->fastapi<1->mlflow-skinny==3.2.0->mlflow) (4.10.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from anyio<5,>=3.6.2->starlette<0.48.0,>=0.40.0->fastapi<1->mlflow-skinny==3.2.0->mlflow) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from anyio<5,>=3.6.2->starlette<0.48.0,>=0.40.0->fastapi<1->mlflow-skinny==3.2.0->mlflow) (1.3.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in c:\users\sai dhruva\appdata\local\programs\python\python310\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.2.0->mlflow) (0.6.1)

[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [31]:
%pip install pyngrok
from pyngrok import ngrok

# Set your authtoken
ngrok.set_auth_token("2nTBPNP5lbwiCq3d1lyml0nPehx_ygDii6V2D77CG3ZurHuW")

# Connect to port 5000
ngrok_tunnel = ngrok.connect(5000, "http")
print("MLflow Tracking UI:", ngrok_tunnel.public_url)
!mlflow ui

Collecting pyngrok
  Using cached pyngrok-7.3.0-py3-none-any.whl.metadata (8.1 kB)
Requirement already satisfied: PyYAML>=5.1 in c:\users\sai dhruva\anaconda3\lib\site-packages (from pyngrok) (6.0.1)
Using cached pyngrok-7.3.0-py3-none-any.whl (25 kB)
Installing collected packages: pyngrok
Successfully installed pyngrok-7.3.0
Note: you may need to restart the kernel to use updated packages.
MLflow Tracking UI: https://f9f16ce30430.ngrok-free.app
^C

In [1]:
#!/usr/bin/env python
# coding: utf-8

import mlflow
import mlflow.sklearn
import pandas as pd
import numpy as np
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Download NLTK data
nltk.download('stopwords', quiet=True)
nltk.download('wordnet', quiet=True)

def preprocess_comment(comment):
    """Preprocess text comments for sentiment analysis"""
    # Convert to lowercase
    comment = comment.lower()

    # Remove trailing and leading whitespaces
    comment = comment.strip()

    # Remove newline characters
    comment = re.sub(r'\n', ' ', comment)

    # Remove non-alphanumeric characters, except punctuation
    comment = re.sub(r'[^A-Za-z0-9\s!?.,]', '', comment)

    # Remove stopwords but retain important ones for sentiment analysis
    stop_words = set(stopwords.words('english')) - {'not', 'but', 'however', 'no', 'yet'}
    comment = ' '.join([word for word in comment.split() if word not in stop_words])

    # Lemmatize the words
    lemmatizer = WordNetLemmatizer()
    comment = ' '.join([lemmatizer.lemmatize(word) for word in comment.split()])

    return comment

def load_and_preprocess_data(url):
    """Load and preprocess the dataset"""
    df = pd.read_csv(url)
    
    # Data cleaning
    df.dropna(inplace=True)
    df.drop_duplicates(inplace=True)
    df = df[~(df['clean_comment'].str.strip() == '')]
    
    # Apply preprocessing
    df['clean_comment'] = df['clean_comment'].apply(preprocess_comment)
    
    return df

def setup_mlflow_experiment(experiment_name="/mlflow/RF Baseline"):
    """Set up MLflow experiment"""
    experiment = mlflow.set_experiment(experiment_name)
    return experiment

def train_baseline_model_with_mlflow(df, experiment_id, vectorizer_max_features=10000, 
                                   n_estimators=200, max_depth=15, test_size=0.2, 
                                   random_state=42):
    """
    Train a baseline Random Forest model with MLflow tracking
    
    Parameters:
    - df: Preprocessed DataFrame
    - experiment_id: MLflow experiment ID
    - vectorizer_max_features: Maximum features for CountVectorizer
    - n_estimators: Number of trees in Random Forest
    - max_depth: Maximum depth of trees
    - test_size: Proportion of test set
    - random_state: Random state for reproducibility
    """
    
    # Vectorize the comments
    vectorizer = CountVectorizer(max_features=vectorizer_max_features)
    X = vectorizer.fit_transform(df['clean_comment']).toarray()
    y = df['category']
    
    # Split the data
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_size, random_state=random_state, stratify=y
    )
    
    with mlflow.start_run(
        experiment_id=experiment_id,
        run_name='RandomForest_Baseline_TrainTestSplit', 
        description="Baseline RandomForest model for sentiment analysis using Bag of Words (BoW) with a simple train-test split"
    ) as run:
        
        # Set tags
        mlflow.set_tag("mlflow.runName", "RandomForest_Baseline_TrainTestSplit")
        mlflow.set_tag("experiment_type", "baseline")
        mlflow.set_tag("model_type", "RandomForestClassifier")
        mlflow.set_tag("description", "Baseline RandomForest model for sentiment analysis using Bag of Words (BoW) with a simple train-test split")

        # Log parameters
        mlflow.log_param("vectorizer_type", "CountVectorizer")
        mlflow.log_param("vectorizer_max_features", vectorizer_max_features)
        mlflow.log_param("n_estimators", n_estimators)
        mlflow.log_param("max_depth", max_depth)
        mlflow.log_param("test_size", test_size)
        mlflow.log_param("random_state", random_state)
        
        # Log dataset info
        mlflow.log_param("dataset_size", len(df))
        mlflow.log_param("training_samples", len(X_train))
        mlflow.log_param("test_samples", len(X_test))

        # Initialize and train the model
        model = RandomForestClassifier(
            n_estimators=n_estimators, 
            max_depth=max_depth, 
            random_state=random_state
        )
        model.fit(X_train, y_train)

        # Make predictions
        y_pred = model.predict(X_test)

        # Calculate metrics
        accuracy = accuracy_score(y_test, y_pred)
        classification_rep = classification_report(y_test, y_pred, output_dict=True)

        # Log metrics
        mlflow.log_metric("accuracy", accuracy)
        
        # Log per-class metrics
        for label, metrics in classification_rep.items():
            if isinstance(metrics, dict):
                for metric, value in metrics.items():
                    mlflow.log_metric(f"{label}_{metric}", value)

        # Create and log confusion matrix
        conf_matrix = confusion_matrix(y_test, y_pred)
        plt.figure(figsize=(8, 6))
        sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues")
        plt.xlabel("Predicted")
        plt.ylabel("Actual")
        plt.title("Confusion Matrix - Baseline Random Forest")
        
        # Save and log the confusion matrix
        confusion_matrix_path = "confusion_matrix_baseline.png"
        plt.savefig(confusion_matrix_path)
        mlflow.log_artifact(confusion_matrix_path)
        plt.close()

        # Log the model
        mlflow.sklearn.log_model(
            model, 
            "random_forest_baseline_model",
            registered_model_name="RandomForest_Baseline_Sentiment"
        )

        # Log the preprocessed dataset
        dataset_path = "preprocessed_dataset.csv"
        df.to_csv(dataset_path, index=False)
        mlflow.log_artifact(dataset_path)

        # Log feature importance (if available)
        if hasattr(model, 'feature_importances_'):
            feature_importance = pd.DataFrame({
                'feature': vectorizer.get_feature_names_out(),
                'importance': model.feature_importances_
            }).sort_values('importance', ascending=False)
            
            importance_path = "feature_importance.csv"
            feature_importance.head(50).to_csv(importance_path, index=False)  # Top 50 features
            mlflow.log_artifact(importance_path)

        print(f"✅ MLflow run completed: {run.info.run_id}")
        print(f"📊 Accuracy: {accuracy:.4f}")
        
        return {
            'run_id': run.info.run_id,
            'model': model,
            'vectorizer': vectorizer,
            'accuracy': accuracy,
            'classification_report': classification_rep,
            'confusion_matrix': conf_matrix
        }

def main():
    """Main function to run the complete pipeline"""
    
    # Data URL
    DATA_URL = 'https://raw.githubusercontent.com/Himanshu-1703/reddit-sentiment-analysis/refs/heads/main/data/reddit.csv'
    
    try:
        # Load and preprocess data
        print("📥 Loading and preprocessing data...")
        df = load_and_preprocess_data(DATA_URL)
        print(f"✅ Data loaded: {len(df)} samples")
        
        # Setup MLflow experiment
        print("🔧 Setting up MLflow experiment...")
        experiment = setup_mlflow_experiment()
        
        # Train model with MLflow tracking
        print("🚀 Training baseline model with MLflow tracking...")
        results = train_baseline_model_with_mlflow(
            df=df,
            experiment_id=experiment.experiment_id,
            vectorizer_max_features=10000,
            n_estimators=200,
            max_depth=15,
            test_size=0.2,
            random_state=42
        )
        
        print("🎯 Training completed successfully!")
        print(f"📈 Final Accuracy: {results['accuracy']:.4f}")
        
        # Save local copy of preprocessed data
        df.to_csv('reddit_preprocessing.csv', index=False)
        print("💾 Preprocessed data saved to 'reddit_preprocessing.csv'")
        
    except Exception as e:
        print(f"❌ Error in main execution: {str(e)}")
        raise

if __name__ == "__main__":
    main()

📥 Loading and preprocessing data...

KeyboardInterrupt: